title: Pokeymoley Server Wiki
description: A wiki for custom content found in the pokeymoley server
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Officiallysp
repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
